 USE [master]
GO
/****** Object:  Database [eCanteenDB]    Script Date: 9/16/2015 11:12:28 PM ******/
CREATE DATABASE [eCanteenDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'eCanteenDB', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\eCanteenDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'eCanteenDB_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\eCanteenDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [eCanteenDB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [eCanteenDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [eCanteenDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [eCanteenDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [eCanteenDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [eCanteenDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [eCanteenDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [eCanteenDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [eCanteenDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [eCanteenDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [eCanteenDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [eCanteenDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [eCanteenDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [eCanteenDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [eCanteenDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [eCanteenDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [eCanteenDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [eCanteenDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [eCanteenDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [eCanteenDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [eCanteenDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [eCanteenDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [eCanteenDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [eCanteenDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [eCanteenDB] SET RECOVERY FULL 
GO
ALTER DATABASE [eCanteenDB] SET  MULTI_USER 
GO
ALTER DATABASE [eCanteenDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [eCanteenDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [eCanteenDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [eCanteenDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [eCanteenDB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'eCanteenDB', N'ON'
GO
USE [eCanteenDB]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 9/16/2015 11:12:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[Email] [nvarchar](256) NOT NULL,
	[Contact] [nvarchar](11) NOT NULL,
	[Employer] [nvarchar](256) NULL,
	[Password] [nvarchar](64) NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[FoodItem]    Script Date: 9/16/2015 11:12:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FoodItem](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[VendorId] [int] NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[Availability] [bit] NOT NULL,
 CONSTRAINT [PK_FoodItem] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Menu]    Script Date: 9/16/2015 11:12:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Menu](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [nvarchar](50) NOT NULL,
	[VendorId] [int] NOT NULL,
 CONSTRAINT [PK_MenuType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[MenuFoodItem]    Script Date: 9/16/2015 11:12:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MenuFoodItem](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MenuId] [int] NOT NULL,
	[FoodItemId] [int] NOT NULL,
 CONSTRAINT [PK_MenuFoodItem] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Order]    Script Date: 9/16/2015 11:12:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NOT NULL,
	[VenderId] [int] NOT NULL,
	[SubTotal] [decimal](18, 2) NOT NULL,
	[ServiceTax] [decimal](18, 2) NOT NULL,
	[Vat] [decimal](18, 2) NOT NULL,
	[Discount] [decimal](18, 2) NOT NULL,
	[Total] [decimal](18, 2) NOT NULL,
	[TimeSlot] [int] NOT NULL,
	[Status] [int] NOT NULL,
	[PaymentStatus] [int] NOT NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[OrderItem]    Script Date: 9/16/2015 11:12:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderItem](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrderId] [int] NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[Quantity] [int] NOT NULL,
	[FoodItemId] [int] NOT NULL,
 CONSTRAINT [PK_OrderItem] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Payment]    Script Date: 9/16/2015 11:12:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Payment](
	[Id] [int] NOT NULL,
	[OrderId] [int] NOT NULL,
	[Amount] [decimal](18, 2) NOT NULL,
	[PaymentStatus] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_Payment] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Site]    Script Date: 9/16/2015 11:12:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Site](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[Address] [nvarchar](256) NOT NULL,
	[Contact] [nvarchar](11) NULL,
	[Owner] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_Site] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Vendor]    Script Date: 9/16/2015 11:12:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vendor](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[Email] [nvarchar](256) NOT NULL,
	[Contact] [nvarchar](11) NOT NULL,
	[Password] [nvarchar](64) NOT NULL,
	[SiteId] [int] NOT NULL,
	[ShopNo] [nvarchar](8) NULL,
 CONSTRAINT [PK_Vendor] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Index [IX_Order]    Script Date: 9/16/2015 11:12:29 PM ******/
CREATE NONCLUSTERED INDEX [IX_Order] ON [dbo].[Order]
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FoodItem]  WITH CHECK ADD  CONSTRAINT [FK_FoodItem_Vendor] FOREIGN KEY([VendorId])
REFERENCES [dbo].[Vendor] ([Id])
GO
ALTER TABLE [dbo].[FoodItem] CHECK CONSTRAINT [FK_FoodItem_Vendor]
GO
ALTER TABLE [dbo].[Menu]  WITH CHECK ADD  CONSTRAINT [FK_Menu_Vendor] FOREIGN KEY([VendorId])
REFERENCES [dbo].[Vendor] ([Id])
GO
ALTER TABLE [dbo].[Menu] CHECK CONSTRAINT [FK_Menu_Vendor]
GO
ALTER TABLE [dbo].[MenuFoodItem]  WITH CHECK ADD  CONSTRAINT [FK_MenuFoodItem_FoodItem] FOREIGN KEY([FoodItemId])
REFERENCES [dbo].[FoodItem] ([Id])
GO
ALTER TABLE [dbo].[MenuFoodItem] CHECK CONSTRAINT [FK_MenuFoodItem_FoodItem]
GO
ALTER TABLE [dbo].[MenuFoodItem]  WITH CHECK ADD  CONSTRAINT [FK_MenuFoodItem_Menu] FOREIGN KEY([MenuId])
REFERENCES [dbo].[Menu] ([Id])
GO
ALTER TABLE [dbo].[MenuFoodItem] CHECK CONSTRAINT [FK_MenuFoodItem_Menu]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Order_Customer] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_Order_Customer]
GO
ALTER TABLE [dbo].[OrderItem]  WITH CHECK ADD  CONSTRAINT [FK_OrderItem_Order] FOREIGN KEY([OrderId])
REFERENCES [dbo].[Order] ([Id])
GO
ALTER TABLE [dbo].[OrderItem] CHECK CONSTRAINT [FK_OrderItem_Order]
GO
ALTER TABLE [dbo].[Payment]  WITH CHECK ADD  CONSTRAINT [FK_Payment_Order] FOREIGN KEY([OrderId])
REFERENCES [dbo].[Order] ([Id])
GO
ALTER TABLE [dbo].[Payment] CHECK CONSTRAINT [FK_Payment_Order]
GO
ALTER TABLE [dbo].[Vendor]  WITH CHECK ADD  CONSTRAINT [FK_Vendor_Site] FOREIGN KEY([SiteId])
REFERENCES [dbo].[Site] ([Id])
GO
ALTER TABLE [dbo].[Vendor] CHECK CONSTRAINT [FK_Vendor_Site]
GO
USE [master]
GO
ALTER DATABASE [eCanteenDB] SET  READ_WRITE 
GO
