//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCanteen.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public FoodItem()
        {
            this.MenuFoodItem = new HashSet<MenuFoodItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid VendorId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<MenuFoodItem> MenuFoodItem { get; set; }
    }
}
