//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCanteen.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.FoodItem = new HashSet<FoodItem>();
            this.Menu = new HashSet<Menu>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string Password { get; set; }
        public System.Guid SiteId { get; set; }
        public string ShopNo { get; set; }
        public bool Active { get; set; }
        public string Logo { get; set; }
    
        public virtual ICollection<FoodItem> FoodItem { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual Site Site { get; set; }
    }
}
